# Generated by Django 5.0.4 on 2024-04-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_customer_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_id',
        ),
    ]
