# Generated by Django 5.0.4 on 2024-04-26 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_customer_customer_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
